graph LR
  SOUTH-TEMPLE[Altar]
  ARAGAIN-FALLS[Aragain Falls]
  ATLANTIS-ROOM[Atlantis Room]
  ATTIC[Attic]
  BAT-ROOM[Bat Room]
  EAST-OF-HOUSE[Behind House]
  CANYON-BOTTOM[Canyon Bottom]
  CANYON-VIEW[Canyon View]
  SMALL-CAVE[Cave]
  TINY-CAVE[Cave]
  CELLAR[Cellar]
  CHASM-ROOM[Chasm]
  GRATING-CLEARING[Clearing]
  CLEARING[Clearing]
  MINE-1[Coal Mine]
  MINE-2[Coal Mine]
  MINE-3[Coal Mine]
  MINE-4[Coal Mine]
  COLD-PASSAGE[Cold Passage]
  CYCLOPS-ROOM[Cyclops Room]
  DAM-ROOM[Dam]
  DAM-BASE[Dam Base]
  DAM-LOBBY[Dam Lobby]
  DAMP-CAVE[Damp Cave]
  DEAD-END-1[Dead End]
  DEAD-END-2[Dead End]
  DEAD-END-3[Dead End]
  DEAD-END-4[Dead End]
  DEAD-END-5[Dead End]
  DEEP-CANYON[Deep Canyon]
  DOME-ROOM[Dome Room]
  LOWER-SHAFT[Drafty Room]
  EAST-OF-CHASM[East of Chasm]
  EW-PASSAGE[East-West Passage]
  EGYPT-ROOM[Egyptian Room]
  END-OF-RAINBOW[End of Rainbow]
  ENGRAVINGS-CAVE[Engravings Cave]
  ENTRANCE-TO-HADES[Entrance to Hades]
  FOREST-1[Forest]
  FOREST-2[Forest]
  MOUNTAINS[Forest]
  FOREST-3[Forest]
  PATH[Forest Path]
  RIVER-1[Frigid River]
  RIVER-2[Frigid River]
  RIVER-3[Frigid River]
  RIVER-4[Frigid River]
  RIVER-5[Frigid River]
  GALLERY[Gallery]
  GAS-ROOM[Gas Room]
  GRATING-ROOM[Grating Room]
  KITCHEN[Kitchen]
  LADDER-BOTTOM[Ladder Bottom]
  LADDER-TOP[Ladder Top]
  LAND-OF-LIVING-DEAD[Land of the Dead]
  LIVING-ROOM[Living Room]
  LOUD-ROOM[Loud Room]
  MACHINE-ROOM[Machine Room]
  MAINTENANCE-ROOM[Maintenance Room]
  MAZE-1[Maze]
  MAZE-2[Maze]
  MAZE-3[Maze]
  MAZE-4[Maze]
  MAZE-5[Maze]
  MAZE-6[Maze]
  MAZE-7[Maze]
  MAZE-8[Maze]
  MAZE-9[Maze]
  MAZE-10[Maze]
  MAZE-11[Maze]
  MAZE-12[Maze]
  MAZE-13[Maze]
  MAZE-14[Maze]
  MAZE-15[Maze]
  MINE-ENTRANCE[Mine Entrance]
  MIRROR-ROOM-1[Mirror Room]
  MIRROR-ROOM-2[Mirror Room]
  NARROW-PASSAGE[Narrow Passage]
  NORTH-OF-HOUSE[North of House]
  NS-PASSAGE[North-South Passage]
  ON-RAINBOW[On the Rainbow]
  RESERVOIR[Reservoir]
  RESERVOIR-NORTH[Reservoir North]
  RESERVOIR-SOUTH[Reservoir South]
  CLIFF-MIDDLE[Rocky Ledge]
  ROUND-ROOM[Round Room]
  SANDY-BEACH[Sandy Beach]
  SANDY-CAVE[Sandy Cave]
  SHAFT-ROOM[Shaft Room]
  SHORE[Shore]
  SLIDE-ROOM[Slide Room]
  SMELLY-ROOM[Smelly Room]
  SOUTH-OF-HOUSE[South of House]
  SQUEEKY-ROOM[Squeaky Room]
  STONE-BARROW[Stone Barrow]
  STRANGE-PASSAGE[Strange Passage]
  IN-STREAM[Stream]
  STREAM-VIEW[Stream View]
  STUDIO[Studio]
  NORTH-TEMPLE[Temple]
  TROLL-ROOM[The Troll Room]
  TIMBER-ROOM[Timber Room]
  TORCH-ROOM[Torch Room]
  TREASURE-ROOM[Treasure Room]
  TWISTING-PASSAGE[Twisting Passage]
  UP-A-TREE[Up a Tree]
  WEST-OF-HOUSE[West of House]
  WHITE-CLIFFS-NORTH[White Cliffs Beach]
  WHITE-CLIFFS-SOUTH[White Cliffs Beach]
  WINDING-PASSAGE[Winding Passage]
  SOUTH-TEMPLE -- north --> NORTH-TEMPLE
  SOUTH-TEMPLE -- down --> TINY-CAVE
  ARAGAIN-FALLS -- north --> SHORE
  ARAGAIN-FALLS -- west --> ON-RAINBOW
  ARAGAIN-FALLS -- up --> ON-RAINBOW
  ATLANTIS-ROOM -- south --> RESERVOIR-NORTH
  ATLANTIS-ROOM -- up --> SMALL-CAVE
  ATTIC -- down --> KITCHEN
  BAT-ROOM -- south --> SQUEEKY-ROOM
  BAT-ROOM -- east --> SHAFT-ROOM
  EAST-OF-HOUSE -- north --> NORTH-OF-HOUSE
  EAST-OF-HOUSE -- south --> SOUTH-OF-HOUSE
  EAST-OF-HOUSE -- east --> CLEARING
  EAST-OF-HOUSE -- west --> KITCHEN
  EAST-OF-HOUSE -- nw --> NORTH-OF-HOUSE
  EAST-OF-HOUSE -- sw --> SOUTH-OF-HOUSE
  EAST-OF-HOUSE -- in --> KITCHEN
  CANYON-BOTTOM -- north --> END-OF-RAINBOW
  CANYON-BOTTOM -- up --> CLIFF-MIDDLE
  CANYON-VIEW -- east --> CLIFF-MIDDLE
  CANYON-VIEW -- west --> FOREST-3
  CANYON-VIEW -- nw --> CLEARING
  CANYON-VIEW -- down --> CLIFF-MIDDLE
  SMALL-CAVE -- north --> MIRROR-ROOM-1
  SMALL-CAVE -- south --> ATLANTIS-ROOM
  SMALL-CAVE -- west --> TWISTING-PASSAGE
  SMALL-CAVE -- down --> ATLANTIS-ROOM
  TINY-CAVE -- north --> MIRROR-ROOM-2
  TINY-CAVE -- west --> WINDING-PASSAGE
  TINY-CAVE -- down --> ENTRANCE-TO-HADES
  CELLAR -- north --> TROLL-ROOM
  CELLAR -- south --> EAST-OF-CHASM
  CELLAR -- up --> LIVING-ROOM
  CHASM-ROOM -- south --> NS-PASSAGE
  CHASM-ROOM -- ne --> RESERVOIR-SOUTH
  CHASM-ROOM -- sw --> EW-PASSAGE
  CHASM-ROOM -- up --> EW-PASSAGE
  GRATING-CLEARING -- south --> PATH
  GRATING-CLEARING -- east --> FOREST-2
  GRATING-CLEARING -- west --> FOREST-1
  CLEARING -- north --> FOREST-2
  CLEARING -- south --> FOREST-3
  CLEARING -- east --> CANYON-VIEW
  CLEARING -- west --> EAST-OF-HOUSE
  MINE-1 -- north --> GAS-ROOM
  MINE-1 -- east --> MINE-1
  MINE-1 -- ne --> MINE-2
  MINE-2 -- north --> MINE-2
  MINE-2 -- south --> MINE-1
  MINE-2 -- se --> MINE-3
  MINE-3 -- south --> MINE-3
  MINE-3 -- east --> MINE-2
  MINE-3 -- sw --> MINE-4
  MINE-4 -- north --> MINE-3
  MINE-4 -- west --> MINE-4
  MINE-4 -- down --> LADDER-TOP
  COLD-PASSAGE -- south --> MIRROR-ROOM-1
  COLD-PASSAGE -- west --> SLIDE-ROOM
  CYCLOPS-ROOM -- east --> STRANGE-PASSAGE
  CYCLOPS-ROOM -- nw --> MAZE-15
  CYCLOPS-ROOM -- up --> TREASURE-ROOM
  DAM-ROOM -- north --> DAM-LOBBY
  DAM-ROOM -- south --> DEEP-CANYON
  DAM-ROOM -- east --> DAM-BASE
  DAM-ROOM -- west --> RESERVOIR-SOUTH
  DAM-ROOM -- down --> DAM-BASE
  DAM-BASE -- north --> DAM-ROOM
  DAM-BASE -- up --> DAM-ROOM
  DAM-LOBBY -- north --> MAINTENANCE-ROOM
  DAM-LOBBY -- south --> DAM-ROOM
  DAM-LOBBY -- east --> MAINTENANCE-ROOM
  DAMP-CAVE -- east --> WHITE-CLIFFS-NORTH
  DAMP-CAVE -- west --> LOUD-ROOM
  DEAD-END-1 -- south --> MAZE-4
  DEAD-END-2 -- west --> MAZE-5
  DEAD-END-3 -- north --> MAZE-8
  DEAD-END-4 -- south --> MAZE-12
  DEAD-END-5 -- north --> LADDER-BOTTOM
  DEEP-CANYON -- east --> DAM-ROOM
  DEEP-CANYON -- nw --> RESERVOIR-SOUTH
  DEEP-CANYON -- sw --> NS-PASSAGE
  DEEP-CANYON -- down --> LOUD-ROOM
  DOME-ROOM -- west --> ENGRAVINGS-CAVE
  DOME-ROOM -- down --> TORCH-ROOM
  LOWER-SHAFT -- south --> MACHINE-ROOM
  LOWER-SHAFT -- east --> TIMBER-ROOM
  LOWER-SHAFT -- out --> TIMBER-ROOM
  EAST-OF-CHASM -- north --> CELLAR
  EAST-OF-CHASM -- east --> GALLERY
  EW-PASSAGE -- north --> CHASM-ROOM
  EW-PASSAGE -- east --> ROUND-ROOM
  EW-PASSAGE -- west --> TROLL-ROOM
  EW-PASSAGE -- down --> CHASM-ROOM
  EGYPT-ROOM -- west --> NORTH-TEMPLE
  EGYPT-ROOM -- up --> NORTH-TEMPLE
  END-OF-RAINBOW -- east --> ON-RAINBOW
  END-OF-RAINBOW -- ne --> ON-RAINBOW
  END-OF-RAINBOW -- sw --> CANYON-BOTTOM
  END-OF-RAINBOW -- up --> ON-RAINBOW
  ENGRAVINGS-CAVE -- east --> DOME-ROOM
  ENGRAVINGS-CAVE -- nw --> ROUND-ROOM
  ENTRANCE-TO-HADES -- south --> LAND-OF-LIVING-DEAD
  ENTRANCE-TO-HADES -- up --> TINY-CAVE
  ENTRANCE-TO-HADES -- in --> LAND-OF-LIVING-DEAD
  FOREST-1 -- north --> GRATING-CLEARING
  FOREST-1 -- south --> FOREST-3
  FOREST-1 -- east --> PATH
  FOREST-2 -- south --> CLEARING
  FOREST-2 -- east --> MOUNTAINS
  FOREST-2 -- west --> PATH
  MOUNTAINS -- north --> FOREST-2
  MOUNTAINS -- south --> FOREST-2
  MOUNTAINS -- west --> FOREST-2
  FOREST-3 -- north --> CLEARING
  FOREST-3 -- west --> FOREST-1
  FOREST-3 -- nw --> SOUTH-OF-HOUSE
  PATH -- north --> GRATING-CLEARING
  PATH -- south --> NORTH-OF-HOUSE
  PATH -- east --> FOREST-2
  PATH -- west --> FOREST-1
  PATH -- up --> UP-A-TREE
  RIVER-1 -- west --> DAM-BASE
  RIVER-1 -- down --> RIVER-2
  RIVER-2 -- down --> RIVER-3
  RIVER-3 -- west --> WHITE-CLIFFS-NORTH
  RIVER-3 -- down --> RIVER-4
  RIVER-4 -- east --> SANDY-BEACH
  RIVER-4 -- west --> WHITE-CLIFFS-SOUTH
  RIVER-4 -- down --> RIVER-5
  RIVER-5 -- east --> SHORE
  GALLERY -- north --> STUDIO
  GALLERY -- west --> EAST-OF-CHASM
  GAS-ROOM -- east --> MINE-1
  GAS-ROOM -- up --> SMELLY-ROOM
  GRATING-ROOM -- sw --> MAZE-11
  GRATING-ROOM -- up --> GRATING-CLEARING
  KITCHEN -- east --> EAST-OF-HOUSE
  KITCHEN -- west --> LIVING-ROOM
  KITCHEN -- up --> ATTIC
  KITCHEN -- down --> STUDIO
  KITCHEN -- out --> EAST-OF-HOUSE
  LADDER-BOTTOM -- south --> DEAD-END-5
  LADDER-BOTTOM -- west --> TIMBER-ROOM
  LADDER-BOTTOM -- up --> LADDER-TOP
  LADDER-TOP -- up --> MINE-4
  LADDER-TOP -- down --> LADDER-BOTTOM
  LAND-OF-LIVING-DEAD -- north --> ENTRANCE-TO-HADES
  LAND-OF-LIVING-DEAD -- out --> ENTRANCE-TO-HADES
  LIVING-ROOM -- east --> KITCHEN
  LIVING-ROOM -- west --> STRANGE-PASSAGE
  LOUD-ROOM -- east --> DAMP-CAVE
  LOUD-ROOM -- west --> ROUND-ROOM
  LOUD-ROOM -- up --> DEEP-CANYON
  MACHINE-ROOM -- north --> LOWER-SHAFT
  MAINTENANCE-ROOM -- south --> DAM-LOBBY
  MAINTENANCE-ROOM -- west --> DAM-LOBBY
  MAZE-1 -- north --> MAZE-1
  MAZE-1 -- south --> MAZE-2
  MAZE-1 -- east --> TROLL-ROOM
  MAZE-1 -- west --> MAZE-4
  MAZE-2 -- south --> MAZE-1
  MAZE-2 -- east --> MAZE-3
  MAZE-3 -- north --> MAZE-4
  MAZE-3 -- west --> MAZE-2
  MAZE-3 -- up --> MAZE-5
  MAZE-4 -- north --> MAZE-1
  MAZE-4 -- east --> DEAD-END-1
  MAZE-4 -- west --> MAZE-3
  MAZE-5 -- north --> MAZE-3
  MAZE-5 -- east --> DEAD-END-2
  MAZE-5 -- sw --> MAZE-6
  MAZE-6 -- east --> MAZE-7
  MAZE-6 -- west --> MAZE-6
  MAZE-6 -- up --> MAZE-9
  MAZE-6 -- down --> MAZE-5
  MAZE-7 -- south --> MAZE-15
  MAZE-7 -- east --> MAZE-8
  MAZE-7 -- west --> MAZE-6
  MAZE-7 -- up --> MAZE-14
  MAZE-8 -- west --> MAZE-8
  MAZE-8 -- ne --> MAZE-7
  MAZE-8 -- se --> DEAD-END-3
  MAZE-9 -- north --> MAZE-6
  MAZE-9 -- south --> MAZE-13
  MAZE-9 -- east --> MAZE-10
  MAZE-9 -- west --> MAZE-12
  MAZE-9 -- nw --> MAZE-9
  MAZE-10 -- east --> MAZE-9
  MAZE-10 -- west --> MAZE-13
  MAZE-10 -- up --> MAZE-11
  MAZE-11 -- ne --> GRATING-ROOM
  MAZE-11 -- nw --> MAZE-13
  MAZE-11 -- sw --> MAZE-12
  MAZE-11 -- down --> MAZE-10
  MAZE-12 -- north --> DEAD-END-4
  MAZE-12 -- east --> MAZE-13
  MAZE-12 -- sw --> MAZE-11
  MAZE-12 -- up --> MAZE-9
  MAZE-13 -- south --> MAZE-10
  MAZE-13 -- east --> MAZE-9
  MAZE-13 -- west --> MAZE-11
  MAZE-13 -- down --> MAZE-12
  MAZE-14 -- south --> MAZE-7
  MAZE-14 -- west --> MAZE-15
  MAZE-14 -- ne --> MAZE-7
  MAZE-14 -- nw --> MAZE-14
  MAZE-15 -- south --> MAZE-7
  MAZE-15 -- west --> MAZE-14
  MAZE-15 -- se --> CYCLOPS-ROOM
  MINE-ENTRANCE -- south --> SLIDE-ROOM
  MINE-ENTRANCE -- west --> SQUEEKY-ROOM
  MINE-ENTRANCE -- in --> SQUEEKY-ROOM
  MIRROR-ROOM-1 -- north --> COLD-PASSAGE
  MIRROR-ROOM-1 -- east --> SMALL-CAVE
  MIRROR-ROOM-1 -- west --> TWISTING-PASSAGE
  MIRROR-ROOM-2 -- north --> NARROW-PASSAGE
  MIRROR-ROOM-2 -- east --> TINY-CAVE
  MIRROR-ROOM-2 -- west --> WINDING-PASSAGE
  NARROW-PASSAGE -- north --> ROUND-ROOM
  NARROW-PASSAGE -- south --> MIRROR-ROOM-2
  NORTH-OF-HOUSE -- north --> PATH
  NORTH-OF-HOUSE -- east --> EAST-OF-HOUSE
  NORTH-OF-HOUSE -- west --> WEST-OF-HOUSE
  NORTH-OF-HOUSE -- se --> EAST-OF-HOUSE
  NORTH-OF-HOUSE -- sw --> WEST-OF-HOUSE
  NS-PASSAGE -- north --> CHASM-ROOM
  NS-PASSAGE -- south --> ROUND-ROOM
  NS-PASSAGE -- ne --> DEEP-CANYON
  ON-RAINBOW -- east --> ARAGAIN-FALLS
  ON-RAINBOW -- west --> END-OF-RAINBOW
  RESERVOIR -- north --> RESERVOIR-NORTH
  RESERVOIR -- south --> RESERVOIR-SOUTH
  RESERVOIR -- west --> IN-STREAM
  RESERVOIR -- up --> IN-STREAM
  RESERVOIR-NORTH -- north --> ATLANTIS-ROOM
  RESERVOIR-NORTH -- south --> RESERVOIR
  RESERVOIR-SOUTH -- north --> RESERVOIR
  RESERVOIR-SOUTH -- east --> DAM-ROOM
  RESERVOIR-SOUTH -- west --> STREAM-VIEW
  RESERVOIR-SOUTH -- se --> DEEP-CANYON
  RESERVOIR-SOUTH -- sw --> CHASM-ROOM
  CLIFF-MIDDLE -- up --> CANYON-VIEW
  CLIFF-MIDDLE -- down --> CANYON-BOTTOM
  ROUND-ROOM -- north --> NS-PASSAGE
  ROUND-ROOM -- south --> NARROW-PASSAGE
  ROUND-ROOM -- east --> LOUD-ROOM
  ROUND-ROOM -- west --> EW-PASSAGE
  ROUND-ROOM -- se --> ENGRAVINGS-CAVE
  SANDY-BEACH -- south --> SHORE
  SANDY-BEACH -- ne --> SANDY-CAVE
  SANDY-CAVE -- sw --> SANDY-BEACH
  SHAFT-ROOM -- north --> SMELLY-ROOM
  SHAFT-ROOM -- west --> BAT-ROOM
  SHORE -- north --> SANDY-BEACH
  SHORE -- south --> ARAGAIN-FALLS
  SLIDE-ROOM -- north --> MINE-ENTRANCE
  SLIDE-ROOM -- east --> COLD-PASSAGE
  SLIDE-ROOM -- down --> CELLAR
  SMELLY-ROOM -- south --> SHAFT-ROOM
  SMELLY-ROOM -- down --> GAS-ROOM
  SOUTH-OF-HOUSE -- south --> FOREST-3
  SOUTH-OF-HOUSE -- east --> EAST-OF-HOUSE
  SOUTH-OF-HOUSE -- west --> WEST-OF-HOUSE
  SOUTH-OF-HOUSE -- ne --> EAST-OF-HOUSE
  SOUTH-OF-HOUSE -- nw --> WEST-OF-HOUSE
  SQUEEKY-ROOM -- north --> BAT-ROOM
  SQUEEKY-ROOM -- east --> MINE-ENTRANCE
  STONE-BARROW -- ne --> WEST-OF-HOUSE
  STRANGE-PASSAGE -- east --> LIVING-ROOM
  STRANGE-PASSAGE -- west --> CYCLOPS-ROOM
  STRANGE-PASSAGE -- in --> CYCLOPS-ROOM
  IN-STREAM -- east --> RESERVOIR
  IN-STREAM -- down --> RESERVOIR
  STREAM-VIEW -- east --> RESERVOIR-SOUTH
  STUDIO -- south --> GALLERY
  NORTH-TEMPLE -- north --> TORCH-ROOM
  NORTH-TEMPLE -- south --> SOUTH-TEMPLE
  NORTH-TEMPLE -- east --> EGYPT-ROOM
  NORTH-TEMPLE -- up --> TORCH-ROOM
  NORTH-TEMPLE -- down --> EGYPT-ROOM
  NORTH-TEMPLE -- out --> TORCH-ROOM
  TROLL-ROOM -- south --> CELLAR
  TROLL-ROOM -- east --> EW-PASSAGE
  TROLL-ROOM -- west --> MAZE-1
  TIMBER-ROOM -- east --> LADDER-BOTTOM
  TIMBER-ROOM -- west --> LOWER-SHAFT
  TORCH-ROOM -- south --> NORTH-TEMPLE
  TORCH-ROOM -- down --> NORTH-TEMPLE
  TREASURE-ROOM -- down --> CYCLOPS-ROOM
  TWISTING-PASSAGE -- north --> MIRROR-ROOM-1
  TWISTING-PASSAGE -- east --> SMALL-CAVE
  UP-A-TREE -- down --> PATH
  WEST-OF-HOUSE -- north --> NORTH-OF-HOUSE
  WEST-OF-HOUSE -- south --> SOUTH-OF-HOUSE
  WEST-OF-HOUSE -- west --> FOREST-1
  WEST-OF-HOUSE -- ne --> NORTH-OF-HOUSE
  WEST-OF-HOUSE -- se --> SOUTH-OF-HOUSE
  WEST-OF-HOUSE -- sw --> STONE-BARROW
  WEST-OF-HOUSE -- in --> STONE-BARROW
  WHITE-CLIFFS-NORTH -- south --> WHITE-CLIFFS-SOUTH
  WHITE-CLIFFS-NORTH -- west --> DAMP-CAVE
  WHITE-CLIFFS-SOUTH -- north --> WHITE-CLIFFS-NORTH
  WINDING-PASSAGE -- north --> MIRROR-ROOM-2
  WINDING-PASSAGE -- east --> TINY-CAVE